### ISSUE TITLE
Exercise 3.1, Answer 6 Clarification

### ISSUE THREAD

**Issue by zeier** [markjprice/cs10dotnet6#10]
The [Bonus Content](https://github.com/markjprice/cs10dotnet6/blob/main/9781801077361_Bonus_Content.pdf) mentions for exercise 3.1, answer 6

> The condition expression is required to evaluate to true or false, but the other two are optional 

This could be misleading, as the condition expression is optional too.

The same applies for answer 8.

**Comment by markjprice** [comment]
Thank you. I have added an erratum for it: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-141---appendix-a---exercise-31--test-your-knowledge
