### ISSUE TITLE
Chapter04 - XML documentation

### ISSUE THREAD

**Issue by cl-ybennani** [markjprice/cs10dotnet6#101]
Hello, 

The quick info tool tip does not does not show what I've written inside the XML comments. I've searched online for a solution, but did not find anything. Below are screenshots of the comment and the tooltips. 

Any reason why I can't get it working?

![image](https://user-images.githubusercontent.com/92038834/185946530-a10f36fe-9cc3-4f6d-b8f3-060aa11abf54.png)

![image](https://user-images.githubusercontent.com/92038834/185946721-7c60fed6-2a33-4a34-9159-a2da61367eb0.png)

**Comment by markjprice** [comment]
Have you read the following errata item?
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-140---documenting-functions-with-xml-comments

**Comment by cl-ybennani** [comment]
duplicate issue that i did not notice
