### ISSUE TITLE
Not getting the results posted in book in chapter 4

### ISSUE THREAD

**Issue by Ed2353** [markjprice/cs10dotnet6#103]
I have triple checked the input of code to create the Trace output by way of the nuget packages and found it solid:
![image](https://user-images.githubusercontent.com/107054628/187274239-472a4369-8472-4dc1-b03e-67958f844d37.png  
The output from the Locals on ts does not match the statements made in the book:
![image](https://user-images.githubusercontent.com/107054628/187275014-b40ec257-c954-405a-9a43-2e9f7dd18e4b.png)
is there code missing ?
I don't know what the purpose of the lesson is.

**Comment by PaddyOfC** [comment]
Hello,

I have the same issue as what is described by the author of the post. I mean I understand the purpose of the lesson but don't succeed to change the info level.

First here is my appsettings.json file :

<img width="284" alt="image" src="https://user-images.githubusercontent.com/129565187/229258780-7af4c8f3-608e-4196-868b-3bd367d8c89f.png">

Then here is the code with the bind:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/129565187/229258891-4f87f704-bcbc-4255-92aa-6feecc79bb5a.png">

I have double checked the code and I am not sure what I am doing wrong.

Any help is welcome.

Thanks!

**Comment by markjprice** [comment]
The .NET team probably introduced the same error as they did in recent packages for .NET 7. Please see the following issue and the fix is likely to use an older package version that is compatible with .NET 6:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-178---reviewing-project-packages

**Comment by markjprice** [comment]
If you have the JSON settings file set to optional then it also might be ignoring it:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-180---reviewing-project-packages

**Comment by markjprice** [comment]
https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-159---reviewing-project-packages
