### ISSUE TITLE
[Chapter 5][Page 208] - Setting value using switch

### ISSUE THREAD

**Issue by cl-ybennani** [markjprice/cs10dotnet6#104]
![image](https://user-images.githubusercontent.com/92038834/189311720-b13edcc1-68f7-43b2-8856-5ab1a09926b5.png)

I'm not sure why I can not use the fall through case statements. Normally I am targeting .Net Standard 2, but i even tried changing it to .net6, and rebuilt the solution, but got the same problem. 

Any reason why this is happening?

**Comment by markjprice** [comment]
You've incorrectly typed a colon : after the word case.

Kind regards,
Mark
