### ISSUE TITLE
Binary number in example is 1 million -- should be 2 million

### ISSUE THREAD

**Issue by kwatsonkairosmgt** [markjprice/cs10dotnet6#105]
In Chapter 2 under Working with Variables, in the following text :

    // three variables that store the number 2 million
    int decimalNotation = 2_000_000;
    int binaryNotation = 0b_0001_1110_1000_0100_1000_0000; 
    int hexadecimalNotation = 0x_001E_8480;

the binary number given is 1 million, not 2 million

**Comment by markjprice** [comment]
No, it is 2 million.

**Comment by kwatsonkairosmgt** [comment]
Apologies you are correct, thought I had double checked.

**Comment by markjprice** [comment]
No worries. :)
