### ISSUE TITLE
OmniSharp: Select Project bug

### ISSUE THREAD

**Issue by johncflorida** [markjprice/cs10dotnet6#11]
In Chapter 01 pg 28 step 6 of the "Adding a second project using Visual Studio Code" section the attempt to launch OmniSharp: Select Project results in an error.

This bug has been raised as an issue (<a  href="https://github.com/OmniSharp/omnisharp-vscode/commit/5103f4925ab21110abcb8ab56aba24100b7e4a63"> #4914</a>) on the OmniSharp Git project.  It appears that the fix has been proposed to the master branch and is currently in release <a href="https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2">1.23.18-beta2</a>.

Based on the comments on pg 28 and pg 41 of Chapter 01, it appears that the use of this command is required in order to have multiple projects in the same workspace.

The current stable that I've installed is 1.23.17.  Is it possible to update the OmniSharp extension in Visual Studio Code to 1.23.18-beta2 so that I can complete these steps?  Or is it better to just wait for the stable release of 1.23.18 and come back to this later?

BTW - Great book so far.  Appreciate your efforts.

**Comment by johncflorida** [comment]
FYI - I'm running VS Code version 1.63.0 commit 2021-12-07T06:26:56.179Z on a Windows 10 machine.

**Comment by markjprice** [comment]
I've just tested with:

OS: Windows 11
Visual Studio Code: November 2021 1.63.0
C# extension: 1.23.17

When trying to use the Command Palette to run the Omnisharp: Select Project command I got the error, "Command 'OmniSharp: Select Project' resulted in an error (Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators. Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp)", as shown in the following screenshot:

![omnisharp-error](https://user-images.githubusercontent.com/14040265/145404220-e4d80970-f879-4724-9c48-89be44e65874.png)

I suggest waiting for the update to the C# extension and OmniSharp. Hopefully it'll be released in a few days. I will leave this issue open and retest once the update is released.

**Comment by markjprice** [comment]
Selecting the project for OmniSharp is not required to have multiple projects in a workspace. It just means you will be missing some IntelliSense and debugging features. A temporary fix is to copy the .vscode folder from the HelloCS project into the TopLevelProgram project. That will enable the missing features.

**Comment by johncflorida** [comment]
Yes, confirmed.  That is the same error I see.  I'll try copying the .vscode folder as suggested.  I am also watching the OmniSharp project for the release of 1.23.18.  Once it's released I will try as well and report back.

**Comment by johncflorida** [comment]
FYI - Just to try it, I installed the 1.23.18-beta2 vsix file using the following instructions ([Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)) using the appropriate system .vsix file ([v1.23.18-beta2 .vsix](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2)).  It appears to have corrected the error above without and new issues so far.  Bodes well for the stable release working as well when it comes out.

**Comment by markjprice** [comment]
Since this is still an active issue (someone else raised it again a few hours ago) I am reopening this issue and adding an erratum.

**Comment by ken-from-the-uk** [comment]
Hi,
Currently the extension c# for Visual Studio Code breaks with a message :-
Command 'OmniSharp: Select Project' resulted in an error (Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators.
Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators.
The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp)

I’m running Windows 11 – in case this is a reason

Work around is that the current version which is 1.23.17 is to move to beta which can be found at 

https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2

I used the csharp-1.23.18-win32-x64.vsix version

It’s installed by the meatballs menu top right of extensions , and selecting ‘install by vsix’

Hope this is helpful

**Comment by carlosbetogomez** [comment]
Hi, 

Had the same issue, looks like it only happens on VSC version 1.63.x, I downgraded the version to 1.62.3 and problem solved.

PD: Thanks for the book and for your effort to support the community.

**Comment by markjprice** [comment]
This issue has now been resolved with the release of C# extension 1.24.0 on January 20, 2022: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
