### ISSUE TITLE
Exploring the PowerShell language has label 3, but no content

### ISSUE THREAD

**Issue by nyanpasus** [markjprice/cs10dotnet6#112]
Hi, mark,

I've found [Exploring the PowerShell language](../tree/main/docs/powershell/powershell-language.md) hasn't  been completed yet，as the same in cs11dotnet7, is there any future update for this?

**Comment by markjprice** [comment]
No, there won't be, for the same reason as for cs11dotnet7: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-330---publishing-a-self-contained-app-page-354---exercise-73--explore-powershell

**Comment by nyanpasus** [comment]
> No, there won't be, for the same reason as for cs11dotnet7: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-330---publishing-a-self-contained-app-page-354---exercise-73--explore-powershell

Thank you for your reply. I think maybe we could add the same content to cs10dotnet6 errata.

**Comment by markjprice** [comment]
Good idea. Done: https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-292---publishing-a-self-contained-app-page-316---exercise-73--explore-powershell
