### ISSUE TITLE
Chapter 14 Layout not being applied to Razor pages

### ISSUE THREAD

**Issue by enderandpeter** [markjprice/cs10dotnet6#113]
I have been greatly enjoying this wonderful book, but I came across a section that I'm not getting to work as described. I've looked a lot online and I cannot find the issue.

I'm in Chapter 14, trying to complete "Using code-behind files with Razor Pages". I've got [my code in a repo](https://github.com/enderandpeter/PracticalApps) so you can take a look. For some reason, the `Pages/Shared/_Layout.cshtml` is not being applied to the Razor pages. I've been looking online and re-reading your instructions and I can't find what I'm doing wrong, but I may be making some silly mistake. The consensus is that if your Layout is not being applied, you must have forgotten the `Pages/_ViewStart.cshtml`, but you will see how it is [clearly present](https://github.com/enderandpeter/PracticalApps/blob/main/Northwind.Web/Pages/_ViewStart.cshtml).

Some suggest using a local kind of relative path to define the Layout, but shouldn't just `_Layout` work? I tried setting it to `~/Pages/Shared/_Layout.cshtml` but it made no difference.

You will see how my code should be up to the point where I can view the sample index page and the initial Suppliers page. Again, `Pages/_ViewStart.cshtml` has the Layout setting, yet when I load pages they are just the HTML slots in the Razor pages without the Layout. Please help me find out what I am missing. 

By the way, I'm trying this on both Mac and Windows and seeing the same result.

Thank you very much.

**Comment by markjprice** [comment]
Hi Spencer,

If you compare your project file: 
https://github.com/enderandpeter/PracticalApps/blob/main/Northwind.Web/Northwind.Web.csproj

With the project file in my repo:
https://github.com/markjprice/cs10dotnet6/blob/main/vs4win/PracticalApps/Northwind.Web/Northwind.Web.csproj

Then you will see the issue. There are entries that remove some folders and files from being correctly processed:
```xml
<ItemGroup>
    <Content Remove="wwwroot\" />
    <Content Remove="Pages\_ViewStart.cshtml" />
    <Content Remove="Pages\Shared\_Layout.cshtml" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
    <Folder Include="Pages\" />
    <Folder Include="Pages\Shared\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Pages\" />
    <None Remove="Pages\index.html" />
    <None Remove="Pages\Shared\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Pages\_ViewStart.cshtml">
      <Generator>RazorTemplatePreprocessor</Generator>
      <LastGenOutput>_ViewStart.cs</LastGenOutput>
    </None>
    <None Include="Pages\Shared\_Layout.cshtml">
      <Generator>RazorTemplatePreprocessor</Generator>
      <LastGenOutput>_Layout.cs</LastGenOutput>
    </None>
  </ItemGroup>
```
You are not the only reader who has had similar issues. It seems that Visual Studio 2022 sometimes adds these entries automatically. I plan to add a new section to the next edition explaining what these entries do and why VS2022 might add them and how to remove them if you start getting "odd" behavior like files seemly to be ignored.

**Comment by enderandpeter** [comment]
Oh dang... thanks so much! Yes I totally noticed VS2022 adding this and I was wondering if it would be a problem, and clearly it is. I'm using VS2022 for Mac by the way.

Thanks so much for the very careful analysis. I'll try this later and let you know. I cannot thank you enough.

**Comment by enderandpeter** [comment]
Okay, I'm finally giving your advice a try and you are totally correct! Removing the ItemGroups with the None elements is now allowing the Layout to apply correctly.

I am now remembering something about those None elements. I recall seeing this with certain C# projects that automatically copy important files to the folder with the executable. From what I remember, this is how you tell `dotnet` to not copy those files because something is already setup to copy them. However, clearly the IDE is mistaken in this case.

Also, I'm seeing that I can totally remove those ItemGroups, just like in your .csproj, the build still works yet I do not see the `.cshtml` files in the Debug or Release folders, so yes I'm curious to know a little more...

Thanks a lot!

**Comment by markjprice** [comment]
Until I've written an article about these issues myself, here's a link to a Microsoft Learn page that you might find useful. 

`.cshtml` pages can use both compile time (default) and runtime (disabled by default) compilation. You would only need to deploy the raw `.cshtml` files if you have also enabled runtime compilation. The idea is that you would then have the option to edit those files and recompile at runtime without doing a full redeployment.

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation
