### ISSUE TITLE
Chapter 1 - Adding .NET Interactive Notebooks to VSCode 

### ISSUE THREAD

**Issue by hil4d63** [markjprice/cs10dotnet6#115]
Hi Mark,

I'm not able to find the extension for .NET Interactive Notebooks in Visual Studio Code on Windows 10.

VS Code Version: 1.76.2
Windows 10 Pro, 21H2
Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz

Thanks,
Hill

**Comment by markjprice** [comment]
The extension has been renamed: https://devblogs.microsoft.com/dotnet/dotnet-interactive-notebooks-is-now-polyglot-notebooks/

**Comment by markjprice** [comment]
Make sure to read all the errata and improvements for the book:
https://github.com/markjprice/cs10dotnet6/tree/main/docs/errata

Here's the first one that's relevant for your issue:
https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-3---pros-and-cons-of-the-net-interactive-notebooks-extension
