### ISSUE TITLE
Chapter07 Packaging and Distributing .NET Types

### ISSUE THREAD

**Issue by omarz7** [markjprice/cs10dotnet6#116]
Packaging a library for NuGet

Page 305 

When modifying the contents of the SharedLibrary.csproj, there is no "<PackageIcon /PackageIcon>" tag in the intellisense, instead a 

"<PackageIconUrl /PackageIconUrl>" tag appears, is that okay and just the intellisense cannot find the "<PackageIcon /PackageIcon>"
tag ?

Also both of "<Pack True /Pack>" and" <PackagePath /PackagePath>" tags in the "<ItemGroup /ItemGroup>" tag.

**Comment by markjprice** [comment]
`PackageIconUrl` is deprecated in favor of `PackageIcon` so your IntelliSense is out-of-date and misleading you:
https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048

Ignore the IntelliSense and use the book tag names.

See the table at the following link and its **MSBuild Property** column for valid tag names:
https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

**Comment by markjprice** [comment]
I have added an item for this too:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-343---packaging-a-library-for-nuget

**Comment by omarz7** [comment]
Thank you Mark, but how to update and make sure that my intellisense is up to date in visual studio ?

**Comment by omarz7** [comment]
Thank you very much Mark.
