### ISSUE TITLE
Chapter 01 Downloading and installing Visual Studio 2022 for Windows [pp 6-7]

### ISSUE THREAD

**Issue by jbertino** [markjprice/cs10dotnet6#118]
In Step 3, the Workloads tab does not have an option for **Mobile Development with .NET**.

The closest choice is **.NET Multi-platform App UI development**.

I think this is the correct one based on the description shown in the example here: https://github.com/markjprice/cs10dotnet6/blob/main/docs/code-editors/B17442_01_02_vs2022.png

This is what the screen looks like today:
![image](https://github.com/markjprice/cs10dotnet6/assets/7320302/295eed61-42a1-4dc7-a471-13fb41ac4099)

Notes:
I checked the errata section and the instructions do not have that update yet either, https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#print-book
The screenshot is from the Modifying window instead of the Installing window because I just chose **.NET Multi-platform App UI development** and installed.

**Comment by markjprice** [comment]
Thank you. I have added this to the errata:
https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-6---downloading-and-installing-visual-studio-2022-for-windows
