### ISSUE TITLE
Encoding strings as byte arrays

### ISSUE THREAD

**Issue by KlarenAlexander** [markjprice/cs10dotnet6#12]
The code on page 391 - "WorkingWithEncodings" always uses UTF-8 regardless of the number entered.  I also checked the Chapter09 solution from the downloaded code and get the same result.  

Not significant, but there is a warning that UTF-7 is obsolete and insecure.

**Comment by markjprice** [comment]
I've just tried running the solution too and it works, as shown in the following screenshots:
![encodings-utf7](https://user-images.githubusercontent.com/14040265/146644369-bde76dc6-7fd3-4814-ab48-893891a344c5.png)
![encodings-unicode](https://user-images.githubusercontent.com/14040265/146644371-8adf645d-6462-4a6b-995b-c356bef44769.png)
Yes, the book points out that UTF-7 should be avoided in Step 5. It is only included for completeness. 
![encodings-utf7-warning](https://user-images.githubusercontent.com/14040265/146644455-8d16d6ad-7f84-4404-9185-e9ca433775b1.png)
Have you tried setting a breakpoint and stepping through your code to discover why your code is not working?

**Comment by markjprice** [comment]
My guess is that your issue is with your keyboard. When you press "1" or "4" what keyboard code does it return?

**Comment by markjprice** [comment]
I have added support for digits entered on the number pad as well as numbers entered at the top row of the keyboard. 
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-391---encoding-strings-as-byte-arrays

**Comment by KlarenAlexander** [comment]
Mark,

Aha!  I was entering using the 10-key pad.  When I used the numeric keyboard, it worked - anther curiosity I'll need to figure out.

Issue resolved.  Sorry to have bothered you.  I've worked through all coding up through Chapter 9.  Excellent book to get my skills up to date after a 5 year hiatus.

Thank you,
Klaren Alexander

**Comment by KlarenAlexander** [comment]
Thanks - nice addition.
Klaren
