### ISSUE TITLE
Polyglot Notebook has replaced .NET Interactive

### ISSUE THREAD

**Issue by ian-wisetech** [markjprice/cs10dotnet6#123]
Polyglot Notebook has now replaced .NET Interactive, so when installing VS code extensions, we should now use Polyglot Notebooks. Besides, when using the command palette to create a new notebook, we should use Polyglot Notebook: Create new blank notebook.

**Comment by markjprice** [comment]
This is the first item in the list of corrections: https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-3---pros-and-cons-of-the-net-interactive-notebooks-extension
