### ISSUE TITLE
Chapter 17 A second operation was started on this context instance before a previous operation completed

### ISSUE THREAD

**Issue by EasonXm** [markjprice/cs10dotnet6#125]
hi! Hello, Mark! I have come to China to read your masterpiece and practice with the code in your book. I am currently stuck in section 4 of Chapter 17 Blazor about adding, deleting and modifying customer information. When I click Create or modify customer information and submit it, I will encounter the error message: “A second operation was started on this context instance before a previous operation completed. This is usually caused  by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading  issues with DbContext ", but if you click Delete, there is no problem. I searched for the solution to this problem, checked that the dependent registration and asynchronous keyword await are OK, and compared the code in the book and the code on github and found nothing different, what did I miss? How to solve this problem? Hope to get your answer, thank you!

**Comment by EasonXm** [comment]
I've asked others about it, and the solution given is to create and modify customer saves to the database using the await keyword, "apparently an oversight on the part of the author


`
public async Task<Customer> CreateCustomerAsync(Customer c)
{
    db.Customers.Add(c);
    await db.SaveChangesAsync();
    return c;
}
 public async Task<Customer> UpdateCustomerAsync(Customer c)
 {
     db.Entry(c).State = EntityState.Modified;
     await db.SaveChangesAsync();
     return c;
 }
`

**Comment by markjprice** [comment]
An alternative is to change the way the data context is registered, as shown in the following errata:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-548---creating-a-class-library-for-a-northwind-database-context

And: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-551---creating-a-class-library-for-entity-models-using-sql-server

**Comment by EasonXm** [comment]
Thank you for your busy reply, I have understood and repaired.


---- Replied Message ----
| From | Mark J. ***@***.***> |
| Date | 3/4/2024 16:46 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |

An alternative is to change the way the data context is registered, as shown in the following errata:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-548---creating-a-class-library-for-a-northwind-database-context

And: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-551---creating-a-class-library-for-entity-models-using-sql-server

**Comment by markjprice** [comment]
My pleasure. Good luck with your projects.

**Comment by EasonXm** [comment]
Hey, Mark! Sorry to trouble you again, I have encountered a new problem, when creating Maui application, the selection of.NET 6 version is not available, but other types of projects are available, I confirm that there is a.net6 SDK installed, why?




 





| |
苏毅思
|
|
厦门九重奏科技有限公司
18559655604
***@***.***
|
---- Replied Message ----
| From | Mark J. ***@***.***> |
| Date | 3/5/2024 15:15 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |

Closed #125 as completed.

**Comment by markjprice** [comment]
The .NET MAUI team have different support levels compared to .NET. They only offer 18 months of support instead of the full three years so you cannot use .NET 6 any more. The steps should work fine with .NET 8.

**Comment by EasonXm** [comment]
I see, but the project created still reported an error, I am according to the error prompt to reload the work debt, thank you very much!



---- Replied Message ----
| From | Mark J. ***@***.***> |
| Date | 03/20/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |

The .NET MAUI team have different support levels compared to .NET. They only offer 18 months of support instead of the full three years so you cannot use .NET 6 any more. The steps should work fine with .NET 8.

**Comment by EasonXm** [comment]
Hey, Mark! Sorry to trouble you again. Regarding the security of maui calling local webapi service, I configured the insecure connection of webapi according to the book and enabled the option of allowing non-secure connection of android and cleared the item to restart maui, but I still couldn't access it. I accessed it through browser and postman. Confirm that the webapi program is normal. The following is the configuration screenshot of webapi and andorid, please kindly guide me again. Thank you very much!
   Also, do the original restrictions on cross-source access in webpi not need to be configured or removed? I've also tried to unregister a piece of code that doesn't work.

  

 

| |
苏毅思
|
|
厦门九重奏科技有限公司
18559655604
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/20/2024 17:02 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |
I see, but the project created still reported an error, I am according to the error prompt to reload the work debt, thank you very much!



---- Replied Message ----
| From | Mark J. ***@***.***> |
| Date | 03/20/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |

The .NET MAUI team have different support levels compared to .NET. They only offer 18 months of support instead of the full three years so you cannot use .NET 6 any more. The steps should work fine with .NET 8.

**Comment by EasonXm** [comment]
Add the screenshot of andorid accessing webapi error message 




| |
苏毅思
|
|
厦门九重奏科技有限公司
18559655604
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/21/2024 14:13 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |
Hey, Mark! Sorry to trouble you again. Regarding the security of maui calling local webapi service, I configured the insecure connection of webapi according to the book and enabled the option of allowing non-secure connection of android and cleared the item to restart maui, but I still couldn't access it. I accessed it through browser and postman. Confirm that the webapi program is normal. The following is the configuration screenshot of webapi and andorid, please kindly guide me again. Thank you very much!
   Also, do the original restrictions on cross-source access in webpi not need to be configured or removed? I've also tried to unregister a piece of code that doesn't work.

  

 

| |
苏毅思
|
|
厦门九重奏科技有限公司
18559655604
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/20/2024 17:02 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |
I see, but the project created still reported an error, I am according to the error prompt to reload the work debt, thank you very much!



---- Replied Message ----
| From | Mark J. ***@***.***> |
| Date | 03/20/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |

The .NET MAUI team have different support levels compared to .NET. They only offer 18 months of support instead of the full three years so you cannot use .NET 6 any more. The steps should work fine with .NET 8.

**Comment by EasonXm** [comment]
Hey, Mark! Sorry to trouble you again. Regarding the security of maui calling local webapi service, I configured the insecure connection of webapi according to the book and enabled the option of allowing non-secure connection of android and cleared the item to restart maui, but I still couldn't access it. I accessed it through browser and postman. Confirm that the webapi program is normal. The following is the configuration screenshot of webapi and andorid, please kindly guide me again. Thank you very much!
   Also, do the original restrictions on cross-source access in webpi not need to be configured or removed? I've also tried to unregister a piece of code that doesn't work.

   

 

| |
苏毅思
|
|
厦门九重奏科技有限公司
18559655604
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/20/2024 17:02 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |
I see, but the project created still reported an error, I am according to the error prompt to reload the work debt, thank you very much!



---- Replied Message ----
| From | Mark J. ***@***.***> |
| Date | 03/20/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |

The .NET MAUI team have different support levels compared to .NET. They only offer 18 months of support instead of the full three years so you cannot use .NET 6 any more. The steps should work fine with .NET 8.

**Comment by EasonXm** [comment]
Hey, Mark! Sorry to trouble you again. Regarding the security of maui calling local webapi service, I configured the insecure connection of webapi according to the book and enabled the option of allowing non-secure connection of android and cleared the item to restart maui, but I still couldn't access it. I accessed it through browser and postman. Confirm that the webapi program is normal. The following is the configuration screenshot of webapi and andorid, please kindly guide me again. Thank you very much!
   

  

 

Also, do the original restrictions on cross-source access in webpi not need to be configured or removed? I've also tried to unregister a piece of code that doesn't work.  

| |
苏毅思
|
|
厦门九重奏科技有限公司
18559655604
***@***.***
|



---- Replied Message ----
| From | ***@***.***> |
| Date | 3/20/2024 17:02 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |
I see, but the project created still reported an error, I am according to the error prompt to reload the work debt, thank you very much!



---- Replied Message ----
| From | Mark J. ***@***.***> |
| Date | 03/20/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [markjprice/cs10dotnet6] Chapter 17 A second operation was started on this context instance before a previous operation completed (Issue #125) |

The .NET MAUI team have different support levels compared to .NET. They only offer 18 months of support instead of the full three years so you cannot use .NET 6 any more. The steps should work fine with .NET 8.
