### ISSUE TITLE
Chapter 14: warning in 14.4.2

### ISSUE THREAD

**Issue by zhangjinshan1990** [markjprice/cs10dotnet6#128]
Hi Mr Price.

I have got a warning  in "asp-for" tag.

![331770554-836153c8-efa9-4dfb-99dd-01f65126c80c](https://github.com/markjprice/cs10dotnet6/assets/59572448/a4fc8223-21fd-4ae4-827f-f6117f55c3ea)

how to solve it?

**Comment by zhangjinshan1990** [comment]
I am using Visual Studio 2022 and .Net 8.0

**Comment by zhangjinshan1990** [comment]
I modified the code，it seems work well
![image](https://github.com/markjprice/cs10dotnet6/assets/59572448/6cea23c1-3937-4e39-b9a9-d1a0f9e5d408)

**Comment by markjprice** [comment]
Thanks, I've added an errata item for this:
https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-597---defining-a-form-to-insert-a-new-supplier
