### ISSUE TITLE
System.NotSupported Exception

### ISSUE THREAD

**Issue by KlarenAlexander** [markjprice/cs10dotnet6#13]
When running Chapter09, "WorkingWithJson", I get a "System.NotSupported Exception saying "System.DateOnly instances are not supported.  Exception message attached.

![SystemNotSupportedException](https://user-images.githubusercontent.com/28513213/146649952-506aa77a-f57a-49d3-8316-d73fdd91caf7.jpg)

**Comment by markjprice** [comment]
Apparently early .NET 6 previews worked (as shown in the output in the book) but support was removed over the summer and our technical reviews did not catch it. 

There is a request to add support for DateOnly and TimeOnly here: https://github.com/dotnet/runtime/issues/53539. Unfortunately it looks like we will all have to wait until .NET 7 for official support to serialize the new DateOnly type with System.Text.Json. 

Meanwhile, we have to implement our own custom JsonConverters, like Jørn H. Dalvik (jornhd) suggests: 
https://github.com/dotnet/runtime/issues/53539#issuecomment-965275504

I have added code solutions and an errata here: 
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-402---controlling-json-processing

**Comment by markjprice** [comment]
Thanks for catching these issues. :)

**Comment by Dreamoochy** [comment]
When I run the code (according to errata), I always get case-insensitive result. I've tried commenting out `PropertyNameCaseInsensitive = true` line, as well as explicit assigning `PropertyNameCaseInsensitive = false` with no success. May it somehow be related to the errata solutions? Or am I doing something wrong?
