### ISSUE TITLE
P28 Tip - Unable to select active project in VS Code - Extension 'ms-dotnettools.csharp' CANNOT use API proposal

### ISSUE THREAD

**Issue by Paul-Schroeder** [markjprice/cs10dotnet6#14]
If you receive the following error when trying to follow the advice on page 28, be aware that there is a bug in the C# for Visual Studio Code extension (version 1.23.17 released on 12/3/2021).  To get around this, you have to either rollback the C# extension to a prior version or manually download / install the v1.24.0-beta1 version found here (expand the collapsed assets section by clicking on the chevron): [C# extension v1.24.0-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases).

**Formal error text:**
Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators. Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp

**Good Practice tip:**
To enable debugging and other useful features, like code formatting and Go to Definition, you must tell OmniSharp which project you are actively working on in Visual Studio Code.  You can quickly toggle active projects by clicking the project/folder to the right of the flame icon on the left side of the status bar.

**Comment by markjprice** [comment]
Thank you for raising this issue. Another reader raised the same issue a few weeks ago. I had expected a non-beta version to be released quickly to solve the problem but since the latest version is still only a beta, I have reopened issue 11 and added an erratum item here: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-28---adding-a-second-project-using-visual-studio-code

**Comment by markjprice** [comment]
This issue has now been resolved with the release of C# extension 1.24.0 on January 20, 2022: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
