### ISSUE TITLE
Are there issues with using VS  Code in a VM?

### ISSUE THREAD

**Issue by ghlouwho** [markjprice/cs10dotnet6#18]
Windows 10, VirtualBox VM

P 151 / 153.  Set a condition < or >, it always stops at that line.

Also, every once in a while, while editing code, instead of a '"' (quote), an '@' appears.  I need to restart the VM, which fixes this, but then it can happen again.

**Comment by markjprice** [comment]
Those do not sound like VM-specific issues but they could be VM-related in that OS configurations are more likely yo change. For example, when double-quote and '@' symbols are swapped it usually indicates that the US and UK keyboards are being swapped. I do not know what could be causing breakpoint conditions with < or > to always stop at that line, unless you have temporarily deactivated the condition. When multiple things go wrong it is easy to assume they are all related.

**Comment by ghlouwho** [comment]
P 151, after entering the condition "HIT RETURN".  If you do not do this, and the condition remains on the screen, the breakpoint is always hit.

https://thegeekpage.com/fix-windows-10-keyboard-language-keeps-changing-on-its-own/.  #8, hopefully, this will fix my keyboard language changing problems.  If not, possible cntrl\shift might, if it happens again.

**Comment by markjprice** [comment]
I'm glad to hear it wasn't a VM problem. I have added an erratum item to highlight that readers should make sure they press Enter: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-152---customizing-breakpoints
