### ISSUE TITLE
Formatting a string

### ISSUE THREAD

**Issue by dpkwhan** [markjprice/cs10dotnet6#20]
On page 83 of the print book, the formatting string is not necessary when outputting the header since ``arg1`` is a string:

```C#
Console.WriteLine(
    format: "{0,-10} {1,6}",
    arg0: "Name",
    arg1: "Count"
);
```

**Comment by markjprice** [comment]
Thank you for spotting this issue. You are correct that the format string does not need the number format code i.e. ":N0". But it does still need the format string to make the column heading right-aligned. I have fixed this issue in the code solutions and added an errata: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-83---understanding-format-strings
