### ISSUE TITLE
Mention property explicitly

### ISSUE THREAD

**Issue by dpkwhan** [markjprice/cs10dotnet6#21]
In section "Setting options with arguments" on page 88 of the print book, it is much clearer if you mention that ``ForegroundColor``, ``BackgroundColor`` and ``CursorSize`` are properties of ``Console``. When I first read this, I thought why you used Pascal case to name a variable, instead of camel case and why you did not specify the type of the variables.

**Comment by markjprice** [comment]
Thank you for raising this issue. I agree with you and will make sure I add this to the text of the next edition. Meanwhile, I have added an improvement: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-88---setting-options-with-arguments
