### ISSUE TITLE
Bonus_Content.pdf p. 149, Ch.4 #3 Answer?

### ISSUE THREAD

**Issue by jbeale1** [markjprice/cs10dotnet6#24]
In the file cs10dotnet6-main/9781801077361_Bonus_Content.pdf
on p. 149 (Ch.4 Question 3 Answer) it reads:
`Answer: F5 saves, compiles, runs, and attaches the debugger; Ctrl or Cmd + F5 saves, compiles, and runs the application with the debugger attached;`
which sounds like F5 and Ctrl+F5 do the same thing. However I think Ctrl+F5 runs without the debugger.

**Comment by markjprice** [comment]
Thank you for raising this issue. I had added it as an erratum item for the fifth edition but somehow the fix got overlooked in the sixth edition too! I have added an item for it here:
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-143---appendix-a---exercise-41--test-your-knowledge
