### ISSUE TITLE
Carousel Not Working in Chapter 15

### ISSUE THREAD

**Issue by johncflorida** [markjprice/cs10dotnet6#27]
I was having issues getting the carousel to actually transition through each picture in the MVC project in Chapter 15.  When loading the page, the first picture would load and that is it.  The carousel was not transitioning to the second picture after the 3000ms interval.

Comparing the code to the example code in the Bootstrap 5 documents ([Bootstrap Docs](https://getbootstrap.com/docs/5.0/components/carousel/)) I can see that there was a change to this code between Bootstrap 4 and Bootstrap 5.  The code on pg 645 & 646 for the carousel needs to be updated to use "data-bs-" versus "data-".

For example this first line of code for the carousel:

`<div id="categories" class="carousel slide" data-ride="carousel" data-interval="3000" data-keyboard="true">`

should be for it to work with the Bootstrap 5 CSS file that was defaulted in the MVC template

`<div id="categories" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000" data-keyboard="true">`

Both date-ride & data-interval need to be changed to data-bs-ride and data-bs-interval.  There are six locations in the code that need to be modified.

When I changed the code to the following, the carousel worked for me:

```
@if (Model is not null)
{
    <div id="categories" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000" data-keyboard="true">
        <ol class="carousel-indicators">
            @for (int c = 0; c < Model.Categories.Count; c++)
            {
                if (c == 0)
                {
                    currentItem = "active";
                }
                else
                {
                    currentItem = "";
                }
                <li data-bs-target="#categories" data-bs-slide-to="@c" class="@currentItem"></li>
            }
        </ol>
        <div class="carousel-inner">
            @for (int c = 0; c < Model.Categories.Count; c++)
            {
                if (c == 0)
                {
                    currentItem = "active";
                }
                else
                {
                    currentItem = "";
                }
                <div class="carousel-item @currentItem">
                    <img class="d-block w-100" src="~/images/category@(Model.Categories[c].CategoryId).jpeg"
                alt="@Model.Categories[c].CategoryName" >
                    <div class="carousel-caption d-none d-md-block">
                        <h2>@Model.Categories[c].CategoryName</h2>
                        <h3>@Model.Categories[c].Description</h3>
                        <p>
                            <a class="btn btn-primary" href="/category/@Model.Categories[c].CategoryId">Views</a>
                        </p>
                    </div>
                </div>
            }
        </div>
        <a class="carousel-control-prev" href="#categories" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#categories" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
}
```

**Comment by markjprice** [comment]
Thank you for raising this issue. I had not noticed that the Bootstrap included with the MVC project template had updated from 4.3.1 to 5.1.0. I will fix this later today.

**Comment by markjprice** [comment]
I have added an erratum item and updated the code solution files: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-645---defining-a-typed-view
