### ISSUE TITLE
Wording should be changed

### ISSUE THREAD

**Issue by ghlouwho** [markjprice/cs10dotnet6#28]
P 171 #4.  "Delete the ex" = ????.  How about Change "Throw ex;", to "throw".  OR, Remove the 'ex' from the 'Throw ex;' statement.

**Comment by ghlouwho** [comment]
P 186 - #2,#4 - did you want to say something about the two different ways that you used to initiate a new person?

**Comment by markjprice** [comment]
You're doing good work identifying areas that the book can be refined. Have you considered becoming a formal reviewer? You could ask Packt to be a technical reviewer for my 7th edition. Packt will tell you what is involved. If you have the time and inclination then you can apply using the following form: https://www.packtpub.com/contact
