### ISSUE TITLE
Minor issue in errata.md - Page 28

### ISSUE THREAD

**Issue by johncflorida** [markjprice/cs10dotnet6#31]
The text for the errata states to install version v1.24.0-beta1 in the text.  But the "download the VSIX" hypertext link points to the v1.23.18-beta2 VSIX file.

![image](https://user-images.githubusercontent.com/30348807/148687585-a50477d3-6632-4111-b9f2-9979613501c5.png)

Note that the overriding bug in OmniSharp was resolved in v1.23.18-beta2 so installing either version will work.

**Comment by markjprice** [comment]
Thanks! Fixed the link.
