### ISSUE TITLE
Example Issue - Chapter 2 target-typed new

### ISSUE THREAD

**Issue by majew7** [markjprice/cs10dotnet6#33]
In **Chapter 2: Using target-typed new to instantiate objects** there is a code example:
```
class Person
{
  public DateTime BirthDate;
}
Person kim = new();
kim.BirthDate = new(1967, 12, 26); // instead of: new DateTime(1967, 12, 26)
```

However, running it in `/Variables/Program.cs` doesn't compile.  Fails with `error CS8803: Top-level statements must precede namespace and type declarations.`

I had to change it to this to get it to build:
```
Person kim = new();
kim.BirthDate = new(1967, 12, 26); // instead of: new DateTime(1967, 12, 26)

class Person
{
  public DateTime BirthDate;
}
```

**Comment by markjprice** [comment]
That is a code example to look at and understand, not a code task (with numbered steps) that you are expected to enter into the program.

**Comment by majew7** [comment]
This is true.  There are no numbered steps here.

**Comment by markjprice** [comment]
I've created an errata item for it too: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-78---using-target-typed-new-to-instantiate-objects
