### ISSUE TITLE
Chapter 1 typo

### ISSUE THREAD

**Issue by exzzy22** [markjprice/cs10dotnet6#34]
Page 32 says

3. Hover your mouse above the code block and click **+ Markup** to add a Markdown cell.

instead of +Markdown

If this is for code stuff only, sorry.

**Comment by markjprice** [comment]
Thank you for spotting this issue. I have added an errata item: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-32---adding-markdown-and-special-commands-to-a-notebook

This GitHub and its issues is for any mistake or improvement that can be made to the book not just code. Thanks again.
