### ISSUE TITLE
Nested and child tasks wrong output

### ISSUE THREAD

**Issue by exzzy22** [markjprice/cs10dotnet6#36]
On page 522 the whole code looks like this

```
using static System.Console;

Task outerTask = Task.Factory.StartNew(OuterMethod);
outerTask.Wait();
WriteLine("Console app is stopping.");

static void OuterMethod()
{
    WriteLine("Outer method starting...");
    Task innerTask = Task.Factory.StartNew(InnerMethod);
    WriteLine("Outer method finished.");
}
static void InnerMethod()
{
    WriteLine("Inner method starting...");
    Thread.Sleep(2000);
    WriteLine("Inner method finished.");
}
```

But the output i get is always

```
Outer method starting...
Outer method finished.
Console app is stopping.
```

Inner method never gets called for some reason. Also later when you do attach to parent i get this

```
Outer method starting...
Outer method finished.
Inner method starting...
Inner method finished.
Console app is stopping.
```

Outer method always starts and finish before inner method starts.

**Comment by markjprice** [comment]
At the bottom of page 522 I say, "Note that, although we wait for the outer task to finish, its inner task does not have to finish as well. In fact, the outer task might finish, and the console app could end, before the inner task even starts!" 

This is the behavior that you are seeing. Continue to step 6 to force the inner method to run by adding the parameter that makes it a child task:
https://github.com/markjprice/cs10dotnet6/blob/main/vs4win/Chapter12/NestedAndChildTasks/Program.cs#L11

**Comment by exzzy22** [comment]
Sorry i missed that somehow, have a really hard time understanding this section.

**Comment by markjprice** [comment]
The performance chapter is one of the trickiest to learn so do not be too concerned. It is the sort of thing that you can come back to if you ever need to implement it in a real project.
