### ISSUE TITLE
Chapter 4 Factorial method issue

### ISSUE THREAD

**Issue by BonayilG** [markjprice/cs10dotnet6#37]
Hi Mark J Price,
First of all , thank you for amazing book. 
Page 137 (Chapter 4) In the Calculating factorials with recursion heading, 0 is returned for 0 in the Factorial method. But 0 factorial equals 1.

**Comment by markjprice** [comment]
Hi, thank you for your kind words. Yes, this is already in the errata: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-137---calculating-factorials-with-recursion
