### ISSUE TITLE
404 Page not found in book-links.md's chapter 6.

### ISSUE THREAD

**Issue by Jasper-Li** [markjprice/cs10dotnet6#38]
404 Page not found. Maybe MS updates their links.
Operator (C# reference):
https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/features-delegates-and-lambda-expressions

source:
https://github.com/markjprice/cs10dotnet6/blob/main/book-links.md#chapter-6---implementing-interfaces-and-inheriting-classes 

Does it update to this site?
https://docs.microsoft.com/en-us/dotnet/standard/delegates-lambdas

**Comment by Jasper-Li** [comment]
Another 404 Page not found.
Interfaces: https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-interfaces

Maybe it moves to this site:
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/interfaces

**Comment by markjprice** [comment]
Yes, it seems the Microsoft Doc team changed the paths for `/tour-of-csharp/` links. Luckily those were the only two. I have fixed them in the books links file. Thank you for raising the issue.
