### ISSUE TITLE
Getting Git

### ISSUE THREAD

**Issue by TomD149** [markjprice/cs10dotnet6#39]
I did not quite follow your intent about getting Git.  On page 38 you use the command _git clone https://github.com/markprice/cs10dotnet6.git_.  The command does not work without the Git App. I located the app at [https://git-scm.com/downloads] for windows (and possibly unix et al).  I installed it and it did perform the clone operation.  Did you want to suggest any configuration advice for the git install?

**Comment by markjprice** [comment]
Hi Tom,

Most Windows users install Visual Studio 2022. On page 7 I give installation instructions to select Git for Windows on the Individual components tab to make sure Git is installed. But some readers do not want to use Git just to get the code solutions so on page 38 I show how to download the files as a ZIP. Apart from using Git to get the code solution, Git is not needed for the book and does not need any special configuration. Also on page 38, I provide the link to download and install Git for use at the command line for Windows and other OSes. 

--Mark
