### ISSUE TITLE
Chage tinytoy.msbuild-project-tools for tintoy.msbuild-project-tools

### ISSUE THREAD

**Issue by cesarfong** [markjprice/cs10dotnet6#4]
Chage tinytoy.msbuild-project-tools for tintoy.msbuild-project-tools

**Comment by cesarfong** [comment]
In the Setting up your development environment SECTION of the book

**Comment by markjprice** [comment]
This is already in the errata: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-8---installing-other-extensions
