### ISSUE TITLE
Chapter 04 - Creating a class library that needs testing

### ISSUE THREAD

**Issue by MarceloCavaliere** [markjprice/cs10dotnet6#41]
Beforehand I would like to say that I have read the issue [issue 23](https://github.com/markjprice/cs10dotnet6/issues/23) but it wasn't enough for me to solve the problem.
Can you do a step by step of this, please?
I didn't find the classlib model neither the xunit.
![image](https://user-images.githubusercontent.com/68856716/156918107-bd7888ab-b04c-49cc-bc4b-42d1ce508571.png)
![image](https://user-images.githubusercontent.com/68856716/156918123-41b92451-dee1-42f5-80dc-d991eb00a461.png)

**Comment by markjprice** [comment]
The instructions in the book tell you to add a new *project* to the *solution*. You are trying to add a new *item* to a *project*. This is why you cannot find the template.

![add-class-library](https://user-images.githubusercontent.com/14040265/156993641-b532266e-0530-4e22-9c9a-f15546f23772.png)

You must:

1. Navigate to **File** | **Add** | **New Project...**.
2. Select **Class Library**.
3. Enter project, location, and solution name.

**Comment by markjprice** [comment]
In the next edition I will add explicit steps to make it clearer.
