### ISSUE TITLE
Converting numbers from cardinal to ordinal

### ISSUE THREAD

**Issue by namutare** [markjprice/cs10dotnet6#42]
Hi,

I noticed the provided code sample under this section in Chapter 04 would create a bug for 11, 12, 13 special cases for numbers greater than 100, i.e. 111, 112, 113. I added a fix, please check it out.

`static string CardinalToOrdinal(int number)
{
    int lastTwoDigits = number % 100;
    
    switch (lastTwoDigits)
    {
        case 11: // special cases from 11th to 13th
        case 12:
        case 13:
            return $"{number}th";
        default:
            int lastDigit = number % 10;

            string suffix = lastDigit switch
            {
                1 => "st",
                2 => "nd",
                3 => "rd",
                _ => "th"
            };
            return $"{number}{suffix}";
    }
}`

**Comment by markjprice** [comment]
Good catch! I have added it to the errata and fixed it in the code solutions.
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-136---converting-numbers-from-cardinal-to-ordinal
