### ISSUE TITLE
Ch12 - Unclear instructions in db setup

### ISSUE THREAD

**Issue by maxinstuff** [markjprice/cs10dotnet6#43]
At the bottom of page 560 there is an instruction to "remove all Fluent API statement that call the ValueGeneratedNever method to configure primary key properties". 

So do you remove only the .ValueGeneratedNever part, or the entire line, or the entire modelBuilder.Entity call?

The instruction doesn't make it very clear and the code example only shows how it looks before, with no view of after.

**Comment by markjprice** [comment]
The "after" view is available in the code solution in the GitHub repository: https://github.com/markjprice/cs10dotnet6/blob/main/vs4win/PracticalApps/Northwind.Common.DataContext.Sqlite/NorthwindContext.cs#L37

**Comment by maxinstuff** [comment]
Thanks Mark - much appreciated!
