### ISSUE TITLE
Chap01 - Notebooks

### ISSUE THREAD

**Issue by mschuweiler** [markjprice/cs10dotnet6#46]
Upon opening Command Palette and entering .net inter as directed I get nothing.  No reference to .NET Interactive.
BTW, I am running the most recent updated version of VS Code on a Windows 10 OS.

**Comment by markjprice** [comment]
Have you installed .NET Interactive Notebooks as directed on page 8 steps 7 and 8?

**Comment by ak804** [comment]
I had to install the Polyglot Notebooks to get the Interactive show up.

**Comment by markjprice** [comment]
Thank you, @ak804. I have added an errata: 
https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-3---pros-and-cons-of-the-net-interactive-notebooks-extension

**Comment by markjprice** [comment]
The 7th edition also has an online section explaining how to use Polyglot Notebooks: https://github.com/markjprice/cs11dotnet7/blob/main/docs/bonus/notebooks.md
I plan to update the screenshots soon.
