### ISSUE TITLE
Building and Consuming Web Services - HttpLogging needs a tweak to appsettings.development.json

### ISSUE THREAD

**Issue by ntsiatinis** [markjprice/cs10dotnet6#47]
Just a quick one - on (or around) page 699 - 'Enabling HTTP logging' - I followed the steps in the book to add HttpLogging, but then didn't see any log messages when calling the localhost:5001/api/customers web service

I solved this by opening up the appsettings.Development.json file and changing 

`"Microsoft.AspNetCore": "Warning"`
to
`"Microsoft.AspNetCore": "Information"`

The logging then appeared on next run.

**Comment by markjprice** [comment]
Thanks! I have added an erratum for this issue: 
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-701---enabling-http-logging
