### ISSUE TITLE
Configuring HTTP Clients using HttpClientFactory - .NET 6.0 bug prevents WebHost.UseUrls from working

### ISSUE THREAD

**Issue by ntsiatinis** [markjprice/cs10dotnet6#48]
Just come across what appears to be a bug in .NET 6.0. I followed the instructions on (or around) page 701 to specify port 5002 for HTTPS however when running the WebApi project it still fired up using port 5001 (which then caused conflict when running the Mvc project).

A quick Google led me to an acknowledgement of the problem here - https://github.com/dotnet/aspnetcore/issues/38185. Looks like it's intended to be fixed in 6.0.4

To get around the issue for now I simply tweaked the WebApi properties/launchsettings.json to specifically use port 5002 (for HTTPS, and tweaked HTTP to 5003 so it didn't conflict). 

Hope this helps. :)

**Comment by markjprice** [comment]
Thanks, Nick. I have added an erratum for this issue:
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-703---configuring-http-clients-using-httpclientfactory
