### ISSUE TITLE
Page 535 connectionString doesn't work

### ISSUE THREAD

**Issue by Chang-Ping** [markjprice/cs10dotnet6#50]
Hi, Mark:

Following the connection string specification on page 535 caused me to see "The certificate chain was issued by an authority that is not trusted." error when the code tries to open the connection.

Adding the following in the connectionString seems to solve the problem.

              "TrustServerCertificate=True;" +

**Comment by markjprice** [comment]
Thank you. I have added this issue to the errata: 
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-535---improving-responsiveness-for-gui-apps
