### ISSUE TITLE
Chapter#6 Bug in Person.TimeTravel  when throwing new Personexception

### ISSUE THREAD

**Issue by cristiano1965** [markjprice/cs10dotnet6#54]
Dear Mark,
I found a small bug.
My compiler issues an error in WriteLine(ex.Message) in the piece of code of Program.cs at page 262.
This is because in the method I indicated in the subject  you write
**throw new PersonException("if you travel back.....");** 
and so you're instatiating the PersonException constructor **using only the string;** in this case you must change the "WriteLine(ex.Message)" to "WriteLine(ex.**ToString()**)" to make it work, but also the innerexception is displayed by the console (and I think you don't want it !!)
My suggestion, to keep your Program.cs untouched, is changing to 
throw new PersonException("if you travel back.....", **new()** ); 
to instantiate the PersonException constructor using **both string and exception**.
Feedback by your side would be much appreciated.
Thanks.
Cristiano

**Comment by markjprice** [comment]
What error does the compiler issue in WriteLine(ex.Message)? There is no reason why it should.

**Comment by cristiano1965** [comment]
Dear Mark,
Probably i forgot to BUILD the Pack again before building Program.cs; indeed now no compile error.
Sorry for disturbing you inappropriately.
Taking the opportunity to make my compliments for this very complete and so exhaustive edition.
Going on to study the next chapters :)

**Comment by markjprice** [comment]
No worries! I'm happy that you are enjoying the book. Good luck!
