### ISSUE TITLE
Chapter 1 - Installing other VS Code Extensions

### ISSUE THREAD

**Issue by joeleetorres** [markjprice/cs10dotnet6#55]
Chapter 1 - Installing other VS Code Extensions
MSBuild project tools 
It says **tinytoy**.msbuild-project-tools instead of **tintoy**.msbuild-project-tools on page 8.

**Comment by markjprice** [comment]
This was added to the errata on 14 November 2021:
https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-8---installing-other-extensions
