### ISSUE TITLE
Chapter02 Using Remove

### ISSUE THREAD

**Issue by HoshyarKarimi** [markjprice/cs10dotnet6#57]
page 61 of the book. I did so but it throws an error
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
<ImportGroup>
	<Using Remove="System.Threading" />
	<Using Include="System.Numerics" />
</ImportGroup>

</Project>
```

**Vocabulary.csproj : error  : The element \<Using\> beneath element \<ImportGroup\> is unrecognized.**
Windows 11
Visual  Studio 2022

**Comment by HoshyarKarimi** [comment]
> page 61 of the book. I did so but it throws an error
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net6.0</TargetFramework>
>     <ImplicitUsings>enable</ImplicitUsings>
>     <Nullable>enable</Nullable>
>   </PropertyGroup>
> 	
> <ImportGroup>
> 	<Using Remove="System.Threading" />
> 	<Using Include="System.Numerics" />
> </ImportGroup>
> 
> </Project>
> ```
> 
> **Vocabulary.csproj : error : The element <Using> beneath element <ImportGroup> is unrecognized.** Windows 11 Visual Studio 2022

Solved by adding tab before new imports. Is it format sensitive?

**Comment by markjprice** [comment]
The problem with your file is not tab formatting, it is that you used `<ImportGroup>` instead of `<ItemGroup>`.

**Comment by HoshyarKarimi** [comment]
> The problem with your file is not tab formatting, it is that you used `<ImportGroup>` instead of `<ItemGroup>`.

Oh. I am blind. Checked it several times but didn't notice. I am sorry

**Comment by markjprice** [comment]
No worries. ;-)
