### ISSUE TITLE
Missing $ on interpolated string.

### ISSUE THREAD

**Issue by GregStevenson** [markjprice/cs10dotnet6#6]
Not sure of page# but towards the end of Chapter 2.
With C# 10, interpolated strings can now be used, as shown in the following code:

private const string fullname = "{firstname} {lastname}";

Without the $, the string is literal and not interpolated.

**Comment by markjprice** [comment]
You are correct. I have created an errata item: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-82---formatting-using-interpolated-strings
