### ISSUE TITLE
Enable loggin not logging 

### ISSUE THREAD

**Issue by cristiano1965** [markjprice/cs10dotnet6#63]
Dear Mark,

Just to let you know that HTTP logging, on page 700,  was logging nothing on the Console and I solved only putting, in appsettings.json inside Logging->LogLevel, the following parameter: "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware": "Information" 

Regards.

Cristiano

**Comment by cristiano1965** [comment]
Closed.

**Comment by markjprice** [comment]
I am guessing you've seen this errata now: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-701---enabling-http-logging
