### ISSUE TITLE
REST Client tests for Northwind.WebApi

### ISSUE THREAD

**Issue by tcrum06** [markjprice/cs10dotnet6#67]
I am currently writing the test create-customer.http using REST Client extension for VS Code. I am using VS 2022 for most of the development but for this particular chapter I am running the API using VS 2022 while executing the REST Client HTTP tests from VS Code.

For the create-customer.http test, I have
`POST https://localhost:5001/api/customers/ HTTP/1.1 
Content-Type: application/json
Content-Length: 301

{
  "customerID": "ABCXY",
  "companyName": "ABC Corp",
  "contactName": "John Smith",
  "contactTitle": "Sir",
  "address": "Main Street",
  "city": "New York",
  "region": "NY",
  "postalCode": "90210",
  "country":  "USA",
  "phone": "(123) 555-1234",
  "fax": null,
  "orders": null
}`

This is matched exactly with the solution file, I have checked it multiple times. I added the XmlIgnore decorator to the Entity model within both EntityModel projects but I am mainly using SQL Server.  When I try to send the request, I am getting a 400 Bad Request response stating that the Orders field of the model is required.

`HTTP/1.1 400 Bad Request
Connection: close
Content-Type: application/problem+json; charset=utf-8
Date: Fri, 27 May 2022 23:28:12 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-579fbc444615574d0b76580a6df60a1b-914ada5f7cf75ac9-00",
    "errors": {
        "Orders": [
            "The Orders field is required."
        ]
    }
}`

The only other decorator for that field is the InverseProperty decorator, although the HashSet is not nullable. Any ideas as to what is causing this?

**Comment by tcrum06** [comment]
All that is necessary is to remove the "orders" key from the create-customer.http dictionary. I was working through the testing with SwaggerUI and realized it was working as intended. If the "orders" key is present, REST Client expects there to be a non-null value with it. The create test file is detailed on page 692. I would suggest adding an entry for it to the Errata, Improvements and Troubleshooting thread.

**Comment by markjprice** [comment]
Thanks, Tim. I have added an errata: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-692---making-other-requests-using-rest-client
