### ISSUE TITLE
Unable to create interactive C# books in Visual Studio Code

### ISSUE THREAD

**Issue by Pierre-Thibault** [markjprice/cs10dotnet6#7]
Hello,

I am unable to create interactive C# books in Visual Studio Code. I do the proper commands and then nothing appears. I have version 1.62.3 of Visual Studio Code. I also tried with Visual Studio Code - Insiders 1.63.0.0 and I have no problem creating interactive books. The problem occurs to me only with version 1.62.3.

Are there other people having the same issue with version 1.62.3 or I'm alone?

Information about my system:

- Windows 10 Enterprise 64 bits version 20H2
- Intel Core i7-6820HQ @ 2.7GHz

**Comment by markjprice** [comment]
I have not heard of anyone else have any problems with 1.62.3. I have just tried upgrading from 1.62.2 to 1.62.3 and then tried to create a new blank .NET Interactive notebook. I had to wait for the latest to install: "Tool 'microsoft.dotnet-interactive' (version '1.0.255902') was successfully installed." Then I could create and use a notebook successfully. You might find that just rebooting and restarting 1.62.3 works. Or wait for 1.63 to release soon. I will leave this issue open for now.

**Comment by umesh2096** [comment]
I also faced similar kind of issue. Diagnostic tool window was showing .net interactive notebook extension is expecting .net5 runtime but it is getting .net6 runtime. I installed both versions and then created the symbolic link for dotnet directory using terminal and issue got fixed

**Comment by markjprice** [comment]
Thank you for adding your feedback, @umesh2096. Yes, I had expected .NET Interactive Notebooks to have been updated to support .NET 6 soon after its release on November 8, but that has not happened yet. .NET Interactive Notebooks currently still need .NET 5 to be installed.

**Comment by Pierre-Thibault** [comment]
I've installed version .net 5, restarted Visual Studio Code 1.62.3 and now things are working fine. I have .net 5 running in Studio Code 1.62.3 and .net 6 running Visual Studio Code - Insiders 1.63.0.0.

@umesh2096 Thank you for the information. I didn't created a symbolic link to fix my issue.
