### ISSUE TITLE
Chapter 10 Database

### ISSUE THREAD

**Issue by HoshyarKarimi** [markjprice/cs10dotnet6#73]
Hello Mark. Honestly I am confused. At page **412** you wrote:

_2. Copy the script to create the Northwind database for SQL Server from the following path in your local Git repository: /sql scripts/Northwind4SQLServer.sql into the WorkingWithEFCore folder._

OK. Done!
Now I have **Northwind4SQLServer.sql** in WorkingWithEFCore folder.

At the page **420** you wrote:

_8. In Solution Explorer, right-click the Northwind.db file and select Properties.
9. In Properties, set Copy to Output Directory to Copy always.
10. Open WorkingWithEFCore.csproj and note the new elements, as shown in the following
markup:_
```
<ItemGroup>
    <None Update="Northwind.db">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
</ItemGroup>
```
What I see is a **Northwind4SQLServer.sql** file, not **Northwind.db** file. I also did _"set Copy to Output Directory to Copy always"_ but what I see is:
```
  <ItemGroup>
    <None Update="Northwind4SQLServer.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```
Do I missed something?

**Comment by markjprice** [comment]
On page 420 I should have made it clearer that steps 8 to 10 only apply to Sqlite and its Northwind.db file. If you use SQL Server then the database file does not exist in the project. You must have not seen the Northwind.db file and right-clicked the .sql script instead. That does not need to be copied to the output directory.

https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-420---defining-the-northwind-database-context-class
