### ISSUE TITLE
Problem with Serialization of DateOnly structure. 

### ISSUE THREAD

**Issue by TomD149** [markjprice/cs10dotnet6#75]
On page 402, the code indicates using the DateOnly type for the PublishDate.  When compiled and run, I receive the message: "Unhandled exception System.NotSupportedException. Serialization and desialization of 'System.DateOnly' instances are not supported.

The code otherwise works fine with DateTime instead of DateOnly.
![Console Serialization DateOnl](https://user-images.githubusercontent.com/98363999/172018784-c2dc00c8-5391-4d92-a831-5cc7312bbdba.jpg)

**Comment by markjprice** [comment]
This is already in the errata: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-402---controlling-json-processing
