### ISSUE TITLE
Importing namespaces. (Hint)

### ISSUE THREAD

**Issue by theFissh** [markjprice/cs10dotnet6#80]
Hey Mark, this is not an issue, but a suggestion.

 If I'm not wrong, about the Chapter 06, "Building Your Own Types with Object-Oriented Programming" (Digital version), you introduce the class libraries, and we use the `WriteLine()` method, like a lot.
 Here is my suggestion:
 In the <projectName>.csproj file, statically import the `System.Console` namespace like this:
 
    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      </PropertyGroup>
      <ItemGroup>
        <Using Include="System.Console" static="true"/>
      </ItemGroup>

    </Project>

 Please notice the static call up there: 

    <Using Include="System.Console" static="true"/>

 So the whole new console application is the following, please notice it is just one line of code long.

    WriteLine("Hello, World! From a single line of code");

 This is the new `projectName.GlobalUsings.g.cs` under `obj\Debug\net6.0\projectName.GlobalUsings.g.cs`

    // <auto-generated/>
    global using global::System;
    global using global::System.Collections.Generic;
    global using global::System.IO;
    global using global::System.Linq;
    global using global::System.Net.Http;
    global using global::System.Threading;
    global using global::System.Threading.Tasks;
    global using static global::System.Console;

 _**please notice the very last line**_

 I scratched the internet looking for a way to do this, and I didn't find anything, until I said, how about If I write `static="true"`. It worked!
 I think everyone needs to know this, and you probably want to add it somewhere in one of your future books.
 I apologize for bothering you, have a great one!

**Comment by markjprice** [comment]
You're right, that is a good idea, and I only thought of it too late in the publishing process for the sixth edition. It was the first improvement that I made to the seventh edition: https://github.com/markjprice/cs11dotnet7

For example: https://github.com/markjprice/cs11dotnet7/blob/main/vs4win/Chapter06/PacktLibrary/PacktLibrary.csproj#L10

**Comment by markjprice** [comment]
I do agree it would be worth telling the sixth edition readers about this too, so I have added an item to the list of improvements: https://github.com/markjprice/cs10dotnet6/blob/main/errata.md#page-84---simplifying-the-usage-of-the-console

**Comment by theFissh** [comment]
Ahh! Always one step ahead!
I appreciate your time and patience. It's good to know it is already included in the next book!
You rock!
