### ISSUE TITLE
Chap1 - .NET Interactive: create notebooks

### ISSUE THREAD

**Issue by ivanalexo** [markjprice/cs10dotnet6#82]
Hi there, I wanted to try running the interactive notebooks on VS Code but I receive an error saying:
![imagen](https://user-images.githubusercontent.com/29745174/174223316-7bcd5e08-d054-46b6-9f1e-b3b35935a42d.png)
I tried to install it by executing the command `dotnet tool install --global Microsoft.dotnet-interactive` but I got an error message saying that the package is incompatible with net 6.0. 
I've the latest version of .net SDK and Visual Studio 2022
![imagen](https://user-images.githubusercontent.com/29745174/174223689-8e506579-b371-4f24-9bc0-126f1a45f5db.png)

**Comment by markjprice** [comment]
Did you first try to install .NET Interactive Notebooks using the Extensions section inside Visual Studio Code? That is the easiest way to install and extension for Visual Studio Code.

Second, you do not install Visual Studio Code extensions using the `dotnet` CLI. 

You use commands like:
```
code --list-extensions
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --uninstall-extension ms-dotnettools.dotnet-interactive-vscode
```
More here: https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

Also, the name of the extension is `ms-dotnettools.dotnet-interactive-vscode`, as shown in this section of my book on page 8:

![image](https://user-images.githubusercontent.com/14040265/174253752-3f83c817-0000-495c-aaac-b60ea8003674.png)

**Comment by ivanalexo** [comment]
Hi Mark, I've installed the extension as was instructed on your book but it was not working, so then I tried using `dotnet` CLI
I've tried uninstalling it `code --install-extension ms-dotnettools.dotnet-interactive-vscode` and the install it again `code --install-extension ms-dotnettools.dotnet-interactive-vscode` but no effect the error still persist.

**Comment by markjprice** [comment]
I've tried Googling but did not find anything helpful. Some people had not installed .NET SDK 6.0 but you already have. Is it just the Create new blank notebook command that gives an error? Or can you open existing notebooks?

**Comment by Dreamoochy** [comment]
Try downloading vsix from official github repository and installing it via **Extensions > Install from VSIX...**

**Comment by Aliabdulraheem** [comment]
**Note:** For folks just starting out like me and trying to install the extension, please note that .Net Interactive Notebooks has been renamed to Polyglot Notebooks so use the prefix **polyglot notebook:** for your commands instead of .Net Interactive.

**Comment by markjprice** [comment]
> **Note:** For folks just starting out like me and trying to install the extension, please note that .Net Interactive Notebooks has been renamed to Polyglot Notebooks so use the prefix **polyglot notebook:** for your commands instead of .Net Interactive.

This is already the first item in the errata for this book: https://github.com/markjprice/cs10dotnet6/blob/main/docs/errata/errata.md#page-3---pros-and-cons-of-the-net-interactive-notebooks-extension
