### ISSUE TITLE
Chapter 08. Identifying positions with the Index type

### ISSUE THREAD

**Issue by Dreamoochy** [markjprice/cs10dotnet6#89]
There's a code:
`````csharp
int[] intArray = new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };

Index i1 =  5; // 0-based index
Index i2 = ^2; // 1-based index

WriteLine($"arr[{i1}] = {intArray[i1]}; arr[{i2}] = {intArray[i2]}");
`````
The result is:
`````
arr[5] = 5; arr[^2] = 8
`````
Why is fromStart-indexing 0-based whereas fromEnd-indexing is 1-based? I expected
`````
intArray[^2] == intArray.Reverse().ToArray()[2]
`````
So `[5]` is the 6th from the start, but `[^2]` is the 2nd form end. It's confusing. I wonder what is the reason behind such behaviour.

**Comment by Dreamoochy** [comment]
I've found the [answer](https://stackoverflow.com/questions/54092458/why-doesnt-the-new-hat-operator-index-from-the-c-sharp-8-array-slicing-feature)
Sorry.

**Comment by markjprice** [comment]
Do you think it would be useful to include a brief explanation and a link to Mads' discussion of that in the next edition?

**Comment by Dreamoochy** [comment]
> Do you think it would be useful to include a brief explanation and a link to Mads' discussion of that in the next edition?

Actually, I was unable to find that comment (among 17 available) under the Mads' article. Therefore I can't be 100% sure the SO anwer shows some **official** position. But I think the fact itself of such behaviour is worth mentioning.

**Comment by Dreamoochy** [comment]
In the spans example you explicitly declare `nameAsSpan`
`````csharp
ReadOnlySpan<char> nameAsSpan    = name.AsSpan();
ReadOnlySpan<char> firstNameSpan = nameAsSpan[0..lenghtOfFirst];
ReadOnlySpan<char> lastNameSpan  = nameAsSpan[^lenghtOfLast..^0];
`````
Is it necessary? The following code seems to work identically:
`````
firstNameSpan = name[0..lenghtOfFirst];
lastNameSpan  = name[^lenghtOfLast..^0];
`````
Are there non-obviuos nuances?

**Comment by Dreamoochy** [comment]
I'm not good in "investigating". But as I can see on Sharplab, `nameAsSpan[x..y]` is converted to `Slice()`, whereas `name[x..y]` is converted to `Substring()`. And when I modify `nameAsSpan`, comletely new variable is implicitly created. That is why `firstNameSpan` and `lastNameSpan` remains unchanged. But I still don't get the point of naming a type `ReadOnly` and allowing to modify the variables of that type. Looks strange and confusing. Maybe I'm just too old and stupid :)
