### ISSUE TITLE
Chapter 09. High-performance JSON processing

### ISSUE THREAD

**Issue by Dreamoochy** [markjprice/cs10dotnet6#92]
The code on p.401 doesn't work for me:
`````csharp
List<Person>? loadedPeople =
  await NewJson.DeserializeAsync(utf8Json: jsonLoad,
  returnType: typeof(List<Person>)) as List<Person>;
`````
It causes CS4033 error. The following code works:
`````csharp
List<Person>? loadedPeople =
  NewJson.Deserialize(utf8Json: jsonLoad,
  returnType: typeof(List<Person>)) as List<Person>;
`````

**Comment by markjprice** [comment]
CS4033 means you have written the statements in a method that is not marked as `async`. If you have written the code in `Program.cs` using top-level statements and .NET SDK 6 then the compiler will create the `Program` class and an `async Main` method for you. Where have you written that statement?

**Comment by markjprice** [comment]
No worries. You've been doing a fantastic job spotting issues and I am very appreciative. 

If you would be interested in being an official reviewer for the 8th edition over Spring/Summer 2023 then let me know and I will forward your details to my publisher. (We already have reviewers for the 7th edition this year.)
