### ISSUE TITLE
Extra semicolon

### ISSUE THREAD

**Issue by theFishHimself** [markjprice/cs10dotnet6#97]
Line contains an additional semicolon, compile error

https://github.com/markjprice/cs10dotnet6/blob/fe168ed0b93150785542e185b064278314929176/vscode/Chapter03/Exercise05/Program.cs#L15

**Comment by markjprice** [comment]
Extra semicolons do not cause compile errors. They are just treated as empty C# statements. For example, you might want to create an infinite loop:
```
while(true)
  ;
```
But it is unneeded and might confuse readers so I have removed it from the code. Thanks!
